name: Lint

on: [pull_request]

jobs:
  shellcheck:
    name: Shellcheck
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run lint
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: 'bats'
