name: Test

on: [pull_request]

jobs:
  bats:
    name: Docker
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run test
        run: docker-compose -f docker/docker-compose-test.yml up
