name: Unit Test

on: [push, pull_request]

jobs:
  bats:
    name: Bats
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bats
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run test
        run: bats tests
